### ISSUE TITLE
Package @unocss/core@0.56.5 has missing documentation

### ISSUE THREAD

**Issue by antfu** [jsdocs-io/web#503]
Please use this issue template to report a package that you know is documented but for which you found missing or incorrect documentation on jsDocs.io.

**Note**: If the package itself has no documentation in the source code, you will need to contact the author of the package.

**Package name**: `@unocss/core`

**Package version**: `0.56.5`

**Problem** (check all that apply using an [x]):

- [x] Missing documentation
- [ ] Partial documentation
- [ ] Incorrect documentation
- [ ] Exposed private documentation
- [ ] Other

**Optionally, briefly describe the problem**:

https://www.jsdocs.io/package/@unocss/core The page only mentions that "Unfortunately type definitions are currently not available for this package" but doesn't show why or how it could be improved.

**Comment by velut** [comment]
Hi @antfu, thanks for opening the issue.

I had to temporarily disable package analysis because some bad actor is trying to scrape every version of every package, thus quickly exhausting the computing power provided by Vercel to the project and increasing my personal costs for maintaining the database of analyzed packages.

I'll try to improve the situation in the next days as I look deeper into the issue, meanwhile I'll add an exemption for packages known to link to jsdocs.io like yours (feel free to list any other package).

**Comment by antfu** [comment]
Thanks! And hope the situation will get better soon!

**Comment by velut** [comment]
I've enabled analysis for `@unocss/core` and the docs page has been updated.

**Comment by antfu** [comment]
Thanks!
