### ISSUE TITLE
Package kontroll@0.1.2 has missing or incorrect documentation

### ISSUE THREAD

**Issue by NamesMT** [jsdocs-io/web#519]
Please use this issue template to report a package that you know is documented but for which you found missing or incorrect documentation on jsDocs.io.

**Note**: If the package itself has no documentation in the source code, you will need to contact the author of the package.

**Package name**: `kontroll`

**Package version**: `0.1.2`

**Problem** (check all that apply using an [x]):

- [x] Missing documentation
- [ ] Partial documentation
- [ ] Incorrect documentation
- [ ] Exposed private documentation
- [ ] Other

**Optionally, briefly describe the problem**:
Hi, quoting @`velut` from https://github.com/jsdocs-io/web/issues/503#issuecomment-1752092272,  
Please help me enable analysis for the package, thanks!

**Comment by velut** [comment]
Hi @NamesMT, thanks for the issue.

Package analysis has been enabled again for some time, so that's not the problem.

The issue here is that the extractor currently does not support `.d.mts` files, which your package provides. I'm in the process of updating the extractor to support also this file format and then your package should be analyzed correctly.

In the meantime, I think you could safely output normal `.d.ts`/`.js` files from your build tool because you have enabled `"type": "module"` in your `package.json` and thus Node and TypeScript already know that they are module files even without the `.mts`/`.mjs` extensions.
